<?php
/* @var $this model_Page */
?>

<!DOCTYPE html>
<html>
    <head>
        <title><?php echo $this->title ?></title>
        <script src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/shared/css/general.css" />
        <script src="/shared/js/menu.js"></script>
        <?php if ($this->userCanEdit()) : ?>
            <script src="/shared/js/admin.js"></script>
        <?php endif; ?>
    </head>
    <body>
    <form method="post" action="<?php echo app::getUrl(array('page' => 'save')) ?>" id="page_edit">
        <input type="hidden" name="page[id]" value="<?php echo $this->id ?>" />

        <div class="header">
            <div class="logo">LOGO</div>
            <div class="login">
                <?php if ($this->user->isLoggedIn()) : ?>
                    <p>Welcome <?php echo $this->user->name ?>!</p>
                    <a href="<?php echo app::getUrl(array('user' => 'logout')) ?>">Logout</a>
                <?php else : ?>
                    <form action="<?php echo app::getUrl(array('user' => 'login')) ?>" method="post" id="user_login">
                        <p>
                            <label for="user_name">name:&nbsp;</label>
                            <input type="text" name="login[name]" id="user_name" value="<?php echo @$this->user->name ?>" />
                        </p>
                        <p>
                            <label for="user_pass">pass:&nbsp;</label>
                            <input type="password" name="login[pass]" id="user_pass" />
                        </p>
                        <button type="submit">Login</button>
                    </form>
                <?php endif; ?>
            </div>
            <div class="topMenu">
                <?php echo $this->renderMenu($this->getMenuItems(), 'ul', 'li') ?>
            </div>
        </div>

        <!--Opening the content container below-->
        <div id="content">
